### ISSUE TITLE
Xsd schema

### ISSUE THREAD

**Issue by romain-malet** [sgadois/ProjetIAWSSOAP#1]
Salut,
J'ai commit sur ma branche un xsd différent du tien que j'avais fait, un mix des deux serait pas mal non ?
Après je me disais qu'il faudrait peut-être une cohérence entre le service REST de l'exigence E4 et ce service en SOAP ... ?

**Comment by sgadois** [comment]
J'ai changé mon xsd pour qu'il reprennent le même format que le fichier xml produit en rest.
Par contre sur ce que t'a fais toi, ça à rien à voir avec ce qui est produit en rest, ou alors j'suis à l'ouest ?

**Comment by romain-malet** [comment]
Non pas du tout à l'ouest ! C'est justement pour ça que je soulevais la chose. Définir comment on fournit ces infos et appliquer le formalisme dans les 2 services. C'était surtout une question en fait !
On pourrait très ne pas fournir les infos dans le même formalisme pour chaque service...

**Comment by sgadois** [comment]
Bah du coup la réponse xml définit actuellement en rest est pas mal, c'etait plus ou moins sur ce que j'étais parti à la base.

**Comment by romain-malet** [comment]
Ok, juste un petit point demain sur ça !
