### ISSUE TITLE
Utilisation du service REST

### ISSUE THREAD

**Issue by romain-malet** [sgadois/ProjetIAWSSOAP#2]
Salut Sébastien,
J'ai jeté un oeil sur ta branche et j'ai vu que tu remettais toute la base de données.
Je me dit qu'il vaudrait mieux utilisé le service REST de l'E4 plutôt que de refaire la même chose dans le service SOAP. Je pense à ça en imaginant que "normalement" les deux services ne sont pas dissociés dans 2 projets, comme on le fait.
SOAP appelle (comme client : https://spring.io/guides/gs/consuming-rest/) le service REST pour fournir la réponse, d'autant que l'xml fourni par REST correspond au contrat soap.
Pour montrer le résultat au travers des tests, on mockerait l'appelle au service REST.
Après je ne me suis pas plongé autant que toi sur la partie SOAP, il y a peut-être des éléments qui m'échappent...
Qu'en penses-tu ?

**Comment by sgadois** [comment]
Hum d'un coté je pense que c'est pas con de réutiliser le service REST vue que la reponse est déjà faites.
D'un autre coté je trouve ça un peu bizarre, sachant que les deux services sont proposés par ugmont, ils ont tout les deux le même accès à la base de données, du coup le service SOAP a pas de raison d'aller interroger REST pour avoir les infos.

**Comment by sgadois** [comment]
Sinon pour le xml que retourne REST, ça correspond pas tout à fait au contrat SOAP.

**Comment by romain-malet** [comment]
Ouais c'est vrai. D'autant plus que le service REST est destiné au front-office et pourrait changer au gré des besoins ce qui obligerait de changer le SOAP...
